# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: Sven Eckelmann <sven@narfation.org>

[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"
